### ISSUE TITLE
Release 1.1.0 crashes when pressing "Add" with Android systems (even with root)

### ISSUE THREAD

**Issue by syyyr** [zacharee/FabricateOverlay#13]
I have the May 2022 patch on my rooted Pixel 6 and using this tutorial, https://forum.xda-developers.com/t/remove-navbar-gesture-pill-and-more-for-pixel-6-pro.4357937/, the app crashes when trying press "Add" after selecting "Android System"

**Comment by yw662** [comment]
Can this issue be reopened since the original problem is not solved ?
