### ISSUE TITLE
[QUESTION] How do this app pass calling identity check?

### ISSUE THREAD

**Issue by aviraxp** [zacharee/FabricateOverlay#2]
The check is here: https://github.com/AndyCGYan/platform_frameworks_base/blob/1476cb5d5716dd105fcdc8fa22e82f77793d6224/services/core/java/com/android/server/om/OverlayManagerService.java#L899

The commit() call should fail if this check is in place.

**Comment by zacharee** [comment]
The commit runs as the shell user, and the given package name is com.android.shell, so that check passes.
